-- =======================================================
-- Service Hub - Full Supabase Database Schema (FIXED v2)
-- Run this script in the Supabase SQL Editor
-- =======================================================

-- -------------------------------------------------------
-- 1. USERS
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT UNIQUE NOT NULL,
    email TEXT DEFAULT '',
    password TEXT NOT NULL,
    role TEXT DEFAULT 'moderator',
    permissions JSONB DEFAULT '[]'::jsonb,
    base_salary NUMERIC DEFAULT 0,
    vodafone_cash TEXT DEFAULT '',
    token TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------
-- 2. PRODUCTS
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC DEFAULT 0,
    duration INTEGER DEFAULT 30,
    description TEXT DEFAULT '',
    category TEXT DEFAULT '',
    inventory_product TEXT DEFAULT '',
    fulfillment_type TEXT DEFAULT 'client_account',
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------
-- 3. INVENTORY SECTIONS
--    FIX: added "type" column used by sectionsAPI.create()
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory_sections (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT DEFAULT 'accounts',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------
-- 4. ACCOUNTS (Inventory)
--    FIX: added two_fa, allowed_uses, current_uses,
--         is_workspace, workspace_members, workspace_cost,
--         created_by — all used by accountsAPI
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounts (
    id TEXT PRIMARY KEY DEFAULT ('ACC-' || extract(epoch from now())::text),
    product_name TEXT DEFAULT '',
    email TEXT DEFAULT '',
    password TEXT DEFAULT '',
    two_fa TEXT DEFAULT '',
    status TEXT DEFAULT 'available',
    allowed_uses INTEGER DEFAULT -1,
    current_uses INTEGER DEFAULT 0,
    is_workspace BOOLEAN DEFAULT false,
    workspace_members INTEGER DEFAULT 0,
    workspace_cost NUMERIC DEFAULT 0,
    created_by TEXT DEFAULT 'Admin',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------
-- 5. CUSTOMERS
--    FIX: added contact_channel, last_order_date
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers (
    id TEXT PRIMARY KEY DEFAULT ('CUS-' || extract(epoch from now())::text),
    name TEXT NOT NULL,
    phone TEXT DEFAULT '',
    email TEXT DEFAULT '',
    contact_channel TEXT DEFAULT 'واتساب',
    last_order_date TIMESTAMPTZ,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------
-- 6. SALES
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE DEFAULT CURRENT_DATE,
    product_name TEXT DEFAULT '',
    original_price NUMERIC DEFAULT 0,
    discount NUMERIC DEFAULT 0,
    final_price NUMERIC DEFAULT 0,
    duration INTEGER DEFAULT 30,
    expiry_date DATE,
    customer_id TEXT,
    customer_name TEXT DEFAULT '',
    customer_phone TEXT DEFAULT '',
    customer_email TEXT DEFAULT '',
    contact_channel TEXT DEFAULT 'واتساب',
    is_paid BOOLEAN DEFAULT false,
    remaining_amount NUMERIC DEFAULT 0,
    payment_method TEXT DEFAULT '',
    wallet_id BIGINT,
    wallet_name TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    moderator TEXT DEFAULT 'Admin',
    assigned_account_email TEXT DEFAULT '',
    assigned_account_id TEXT,
    from_inventory BOOLEAN DEFAULT false,
    sale_type TEXT DEFAULT 'personal',
    workspace_email TEXT DEFAULT '',
    is_activated BOOLEAN DEFAULT false,
    customer_password TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------
-- 7. EXPENSES
--    FIX: added "type" and "expense_category" columns
--         used by expensesAPI (was "category" only before)
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT DEFAULT 'مصروف عام',
    amount NUMERIC DEFAULT 0,
    description TEXT DEFAULT '',
    expense_category TEXT DEFAULT 'daily',
    wallet_id TEXT DEFAULT '',
    wallet_name TEXT DEFAULT '',
    date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------
-- 8. WALLETS
--    FIX: added initial_balance, created_by columns
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    currency TEXT DEFAULT 'EGP',
    initial_balance NUMERIC DEFAULT 0,
    balance NUMERIC DEFAULT 0,
    type TEXT DEFAULT 'cash',
    account_number TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    created_by TEXT DEFAULT 'Admin',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------
-- 9. WALLET TRANSACTIONS
--    FIX: added "source" column used by walletsAPI
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS wallet_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT,
    type TEXT NOT NULL,
    amount NUMERIC DEFAULT 0,
    balance_after NUMERIC DEFAULT 0,
    description TEXT DEFAULT '',
    source TEXT DEFAULT 'يدوي',
    reference_type TEXT DEFAULT 'manual',
    created_by TEXT DEFAULT 'Admin',
    date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------
-- 10. ATTENDANCE
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    date TEXT NOT NULL,
    check_in TEXT,
    bonus NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------
-- 11. PROBLEMS
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT,
    customer_name TEXT DEFAULT '',
    phone_number TEXT DEFAULT '',
    product_name TEXT DEFAULT '',
    description TEXT DEFAULT '',
    replacement_account_id TEXT,
    is_resolved BOOLEAN DEFAULT false,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------
-- 12. QUICK LINKS
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS quick_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    url TEXT NOT NULL,
    created_by TEXT DEFAULT 'Admin',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------
-- 13. EMPLOYEES
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT DEFAULT '',
    role TEXT DEFAULT '',
    base_salary NUMERIC DEFAULT 0,
    bonus NUMERIC DEFAULT 0,
    deductions NUMERIC DEFAULT 0,
    absence_days INTEGER DEFAULT 0,
    absence_deduction_per_day NUMERIC DEFAULT 0,
    notes TEXT DEFAULT '',
    is_active BOOLEAN DEFAULT true,
    join_date DATE DEFAULT CURRENT_DATE,
    pay_day TEXT DEFAULT 'thursday',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------
-- 14. SALARY PAYMENTS
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS salary_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT,
    amount NUMERIC DEFAULT 0,
    payment_date DATE DEFAULT CURRENT_DATE,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------
-- 15. EMPLOYEE ACTIONS
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS employee_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT,
    action_type TEXT NOT NULL,
    amount NUMERIC DEFAULT 0,
    description TEXT DEFAULT '',
    action_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------
-- 16. CUSTOM SHEETS DATA
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS custom_sheets_data (
    sheet_id TEXT PRIMARY KEY,
    records JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------
-- 17. CUSTOM SHEETS CONFIG
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS custom_sheets_config (
    id TEXT PRIMARY KEY DEFAULT 'main_config',
    config JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =======================================================
-- ALTER EXISTING TABLES — add missing columns safely
-- (safe to run on existing databases)
-- =======================================================

-- users — MUST come first so the INSERT below works on existing tables
ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS base_salary NUMERIC DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS vodafone_cash TEXT DEFAULT '';

-- accounts — add missing columns if not exist
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS two_fa TEXT DEFAULT '';
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS allowed_uses INTEGER DEFAULT -1;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS current_uses INTEGER DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS is_workspace BOOLEAN DEFAULT false;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS workspace_members INTEGER DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS workspace_cost NUMERIC DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS created_by TEXT DEFAULT 'Admin';

-- inventory_sections — add type column
ALTER TABLE inventory_sections ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'accounts';

-- expenses — add missing columns
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'مصروف عام';
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS expense_category TEXT DEFAULT 'daily';
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS wallet_id TEXT DEFAULT '';
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS wallet_name TEXT DEFAULT '';

-- customers — add missing columns
ALTER TABLE customers ADD COLUMN IF NOT EXISTS contact_channel TEXT DEFAULT 'واتساب';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS last_order_date TIMESTAMPTZ;

-- wallets — add missing columns
ALTER TABLE wallets ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'EGP';
ALTER TABLE wallets ADD COLUMN IF NOT EXISTS initial_balance NUMERIC DEFAULT 0;
ALTER TABLE wallets ADD COLUMN IF NOT EXISTS created_by TEXT DEFAULT 'Admin';

-- wallet_transactions — add source column
ALTER TABLE wallet_transactions ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'يدوي';

-- sales — ensure customer_id is TEXT (the API uses TEXT IDs like 'CUS-...')
-- Note: if your existing column is BIGINT, you may need to migrate manually.
ALTER TABLE sales ADD COLUMN IF NOT EXISTS workspace_email TEXT DEFAULT '';
ALTER TABLE sales ADD COLUMN IF NOT EXISTS is_activated BOOLEAN DEFAULT false;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS customer_password TEXT DEFAULT '';

-- =======================================================
-- DISABLE ROW LEVEL SECURITY (RLS) FOR DIRECT ACCESS
-- NOTE: For production, consider enabling RLS with proper policies
-- =======================================================
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_sections DISABLE ROW LEVEL SECURITY;
ALTER TABLE accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE wallets DISABLE ROW LEVEL SECURITY;
ALTER TABLE wallet_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE problems DISABLE ROW LEVEL SECURITY;
ALTER TABLE quick_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE salary_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE employee_actions DISABLE ROW LEVEL SECURITY;
ALTER TABLE custom_sheets_data DISABLE ROW LEVEL SECURITY;
ALTER TABLE custom_sheets_config DISABLE ROW LEVEL SECURITY;

-- =======================================================
-- ENABLE REALTIME FOR SYNC (required for postgres_changes)
-- =======================================================
DO $$
BEGIN
  -- Safely add tables to realtime publication
  PERFORM 1 FROM pg_publication WHERE pubname = 'supabase_realtime';
  IF FOUND THEN
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE sales;
    EXCEPTION WHEN duplicate_object THEN NULL; END;
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE products;
    EXCEPTION WHEN duplicate_object THEN NULL; END;
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE accounts;
    EXCEPTION WHEN duplicate_object THEN NULL; END;
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE customers;
    EXCEPTION WHEN duplicate_object THEN NULL; END;
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE inventory_sections;
    EXCEPTION WHEN duplicate_object THEN NULL; END;
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE problems;
    EXCEPTION WHEN duplicate_object THEN NULL; END;
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE users;
    EXCEPTION WHEN duplicate_object THEN NULL; END;
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE custom_sheets_data;
    EXCEPTION WHEN duplicate_object THEN NULL; END;
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE custom_sheets_config;
    EXCEPTION WHEN duplicate_object THEN NULL; END;
  END IF;
END $$;

-- =======================================================
-- RPC FUNCTION: servicehub_sell_account
-- Used by sheetSync.js → sellCloudAccount()
-- Atomically saves a sheet record AND marks account as sold
-- =======================================================
CREATE OR REPLACE FUNCTION servicehub_sell_account(
    p_record JSONB,
    p_account_id TEXT
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    v_sheet_id TEXT;
    v_existing_records JSONB;
    v_new_records JSONB;
BEGIN
    -- Extract sheet_id from the record
    v_sheet_id := p_record->>'sheetId';
    IF v_sheet_id IS NULL THEN
        v_sheet_id := p_record->>'sheet_id';
    END IF;
    IF v_sheet_id IS NULL THEN
        v_sheet_id := 'client_data'; -- default fallback
    END IF;

    -- Get existing records for this sheet
    SELECT records INTO v_existing_records
    FROM custom_sheets_data
    WHERE sheet_id = v_sheet_id;

    IF v_existing_records IS NULL THEN
        v_existing_records := '[]'::jsonb;
    END IF;

    -- Append the new record
    v_new_records := v_existing_records || jsonb_build_array(p_record);

    -- Upsert the sheet data
    INSERT INTO custom_sheets_data (sheet_id, records, updated_at)
    VALUES (v_sheet_id, v_new_records, NOW())
    ON CONFLICT (sheet_id) DO UPDATE
    SET records = v_new_records,
        updated_at = NOW();

    -- Update account status if an account_id was provided
    IF p_account_id IS NOT NULL AND p_account_id != '' THEN
        UPDATE accounts
        SET
            current_uses = COALESCE(current_uses, 0) + 1,
            status = CASE
                WHEN allowed_uses = -1 THEN 'used'
                WHEN COALESCE(current_uses, 0) + 1 >= allowed_uses THEN 'completed'
                ELSE 'used'
            END
        WHERE id = p_account_id;
    END IF;
END;
$$;

-- =======================================================
-- SEED DEFAULT ADMIN USER
-- NOTE: The password below is hashed with bcrypt (rounds=10)
-- Plain text: Service2030@
-- IMPORTANT: Change this password after first login!
-- =======================================================
INSERT INTO users (username, password, role, permissions)
VALUES (
    'support@servicevip.com',
    '$2b$10$iwTGr2OqdN7r38Bb82FC8eFOzzARVcFpvi7O.sZf4THFn4uE8.7TG',
    'admin',
    '["all"]'::jsonb
)
ON CONFLICT (username) DO NOTHING;

-- After the user is inserted, update their email (safe — column added above)
UPDATE users
SET email = 'support@servicevip.com'
WHERE username = 'support@servicevip.com' AND (email IS NULL OR email = '');

-- =======================================================
-- INDEXES for performance
-- =======================================================
CREATE INDEX IF NOT EXISTS idx_sales_date ON sales(date DESC);
CREATE INDEX IF NOT EXISTS idx_sales_customer_id ON sales(customer_id);
CREATE INDEX IF NOT EXISTS idx_sales_product_name ON sales(product_name);
CREATE INDEX IF NOT EXISTS idx_accounts_product_name ON accounts(product_name);
CREATE INDEX IF NOT EXISTS idx_accounts_status ON accounts(status);
CREATE INDEX IF NOT EXISTS idx_customers_name ON customers(name);
CREATE INDEX IF NOT EXISTS idx_problems_is_resolved ON problems(is_resolved);
CREATE INDEX IF NOT EXISTS idx_attendance_user_date ON attendance(user_id, date);
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_wallet_id ON wallet_transactions(wallet_id);
CREATE INDEX IF NOT EXISTS idx_employees_is_active ON employees(is_active);

-- =======================================================
-- DISABLE ROW LEVEL SECURITY (RLS) FOR ALL TABLES
-- This application manages authentication & permissions in-app.
-- Disabling RLS allows the frontend client to query the database.
-- =======================================================
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_sections DISABLE ROW LEVEL SECURITY;
ALTER TABLE accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE wallets DISABLE ROW LEVEL SECURITY;
ALTER TABLE wallet_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE problems DISABLE ROW LEVEL SECURITY;
ALTER TABLE quick_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE salary_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE employee_actions DISABLE ROW LEVEL SECURITY;
ALTER TABLE custom_sheets_data DISABLE ROW LEVEL SECURITY;
ALTER TABLE custom_sheets_config DISABLE ROW LEVEL SECURITY;

-- Grant access to anon and authenticated roles
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated;
